package com.example.gymformcoach.core.coach

import com.example.gymformcoach.core.analysis.AiCoachApiClient
import com.example.gymformcoach.core.data.AppDatabase
import com.example.gymformcoach.core.data.BodyWeightRepository
import com.example.gymformcoach.core.data.Exercise
import com.example.gymformcoach.core.data.ExerciseSessionRepository
import com.example.gymformcoach.core.data.ExerciseType
import com.example.gymformcoach.core.data.PlanRepository
import com.example.gymformcoach.core.data.RoutineExercise
import com.example.gymformcoach.core.data.RoutineRepository
import com.example.gymformcoach.core.data.UserProfile
import com.example.gymformcoach.core.data.WeeklyPlanEntry
import com.example.gymformcoach.core.progression.MuscleFatigue
import com.example.gymformcoach.core.utils.PreferenceManager
import kotlinx.coroutines.flow.first
import kotlinx.serialization.json.Json
import java.time.LocalDate

sealed class CoachResult {
    data class Ready(val plan: PlanValidator.ValidatedPlan) : CoachResult()
    data class Revision(val revision: PlanRevision) : CoachResult()
    data class Unavailable(val reason: String) : CoachResult()
}

/**
 * §17D. Shares the LLM runtime (§9.6's [AiCoachApiClient]/endpoint settings)
 * and nothing else with the post-set form analysis - kept in its own package
 * so form analysis and programming decisions stay independently debuggable.
 *
 * Off by default (§17D.1) - callers gate on `PreferenceManager.aiCoachEnabled`
 * before ever reaching this class; it doesn't check the flag itself so it
 * stays testable without Android context leaking into the "should we even
 * try" decision.
 */
class TrainingCoachRepository(
    private val database: AppDatabase,
    private val preferenceManager: PreferenceManager
) {
    private val json = Json { ignoreUnknownKeys = true; isLenient = true }

    /** §17D.2. */
    suspend fun generatePlan(): CoachResult {
        val profile = database.userProfileDao().getProfileOnce()
        val catalog = filteredCatalog(profile)
        if (catalog.isEmpty()) {
            return CoachResult.Unavailable("No exercises match your available equipment - add equipment in Settings first.")
        }

        val prompt = buildGenerationPrompt(profile, catalog)
        val raw = requestJson(prompt) ?: return CoachResult.Unavailable(
            "AI coach unavailable - check your local server connection."
        )

        val proposal = runCatching { json.decodeFromString(TrainingPlanProposal.serializer(), raw) }
            .getOrElse { return CoachResult.Unavailable("The coach's response wasn't valid - try again.") }

        val validated = PlanValidator.validate(proposal, catalog.map { it.name }.toSet())
        if (validated.isEmpty) {
            return CoachResult.Unavailable("The coach couldn't build a usable plan from your available exercises.")
        }
        return CoachResult.Ready(validated)
    }

    /** §17D.2: writes the proposal through the normal repository path - nothing downstream knows the Coach was involved. */
    suspend fun applyPlan(plan: PlanValidator.ValidatedPlan) {
        val routineRepository = RoutineRepository(database)
        val planRepository = PlanRepository(database)
        val routineIdByName = mutableMapOf<String, String>()

        for (routine in plan.proposal.routines) {
            val exercises = routine.exercises.mapIndexed { index, e ->
                RoutineExercise(
                    routineId = "",
                    exerciseId = e.exerciseId,
                    orderIndex = index,
                    targetWeightKg = 0f, // no history assumption; the progression engine's "no history" path prompts for a working weight (§5.4)
                    targetReps = (e.repRangeMin + e.repRangeMax) / 2,
                    targetSets = e.sets,
                    progressionRuleOverride = null
                )
            }
            val id = routineRepository.saveRoutine(
                name = routine.name,
                description = "Generated by the AI Coach.",
                exercises = exercises,
                progressionRule = routine.progressionRule
            )
            routineIdByName[routine.name] = id
        }

        for (assignment in plan.proposal.weeklyPlan) {
            val routineId = routineIdByName[assignment.routineName] ?: continue
            planRepository.assignDay(assignment.dayOfWeek, routineId)
        }
    }

    /**
     * §17D.3: each diff item is applied independently, through the same
     * repository writes a manual edit would use - nothing downstream needs to
     * know the Coach suggested it. Items the caller didn't accept are simply
     * never passed in.
     */
    suspend fun applyRevision(items: List<PlanDiffItem>) {
        val routineRepository = RoutineRepository(database)
        val allRoutines = database.routineDao().getRoutineSummaries().first()

        for (item in items) {
            val routineSummary = allRoutines.firstOrNull { it.name == item.routineName } ?: continue
            val exercises = database.routineDao().getRoutineExercisesOnce(routineSummary.id).toMutableList()

            when (item) {
                is PlanDiffItem.SwapExercise -> {
                    val target = exercises.firstOrNull { it.exerciseId == item.oldExerciseId }
                    if (target != null) {
                        database.routineDao().updateRoutineExercise(
                            target.copy(exerciseId = item.newExerciseId, updatedAt = System.currentTimeMillis())
                        )
                    }
                }
                is PlanDiffItem.AdjustVolume -> {
                    val target = exercises.firstOrNull { it.exerciseId == item.exerciseId }
                    if (target != null) {
                        database.routineDao().updateRoutineExercise(
                            target.copy(targetSets = item.newSets, updatedAt = System.currentTimeMillis())
                        )
                    }
                }
                is PlanDiffItem.AddExercise -> {
                    database.routineDao().insertRoutineExercises(
                        listOf(
                            RoutineExercise(
                                routineId = routineSummary.id,
                                exerciseId = item.exerciseId,
                                orderIndex = exercises.size,
                                targetWeightKg = 0f,
                                targetReps = (item.repRangeMin + item.repRangeMax) / 2,
                                targetSets = item.sets
                            )
                        )
                    )
                }
            }
        }
    }

    /**
     * §17D.3: on request only in this build (no automatic weekly cadence
     * scheduler was added - a future WorkManager job could call this the same
     * way §14's reminder worker calls PlanRepository).
     */
    suspend fun revisePlan(): CoachResult {
        val profile = database.userProfileDao().getProfileOnce()
        val catalog = filteredCatalog(profile)
        val prompt = buildRevisionPrompt(catalog) ?: return CoachResult.Unavailable(
            "Not enough logged history yet to suggest a revision."
        )

        val raw = requestJson(prompt) ?: return CoachResult.Unavailable(
            "AI coach unavailable - check your local server connection."
        )
        val revision = runCatching { parseRevision(raw) }
            .getOrElse { return CoachResult.Unavailable("The coach's response wasn't valid - try again.") }

        return CoachResult.Revision(revision)
    }

    // ---- prompt construction ----

    /**
     * §17D.4: onboarding's "movements to avoid" is applied as a catalog filter
     * *before* the prompt - the excluded exercises are simply never offered,
     * never explained to the model, never invited as something to reason
     * about. Equipment filtering is the existing §15.1 rule.
     */
    private suspend fun filteredCatalog(profile: UserProfile?): List<Exercise> {
        val all = database.exerciseDao().getAll().first()
        val equipment = preferenceManager.equipment
        val avoid = (profile?.trainingLimitations ?: preferenceManager.trainingLimitations)
            .lowercase()
            .split(Regex("[,;\\n]"))
            .map { it.trim() }
            .filter { it.isNotBlank() }

        val equipmentFiltered = if (equipment.isEmpty() || "Full gym" in equipment) {
            all
        } else {
            val allowedCategories = mutableSetOf<String>()
            if ("Dumbbells only" in equipment) allowedCategories += "Dumbbell"
            if ("Barbell + rack" in equipment) allowedCategories += "Free Weight"
            if ("Bodyweight only" in equipment) allowedCategories += "Bodyweight"
            if ("Resistance bands" in equipment) allowedCategories += "Cable"
            all.filter { it.category in allowedCategories }
        }

        if (avoid.isEmpty()) return equipmentFiltered
        return equipmentFiltered.filterNot { exercise ->
            avoid.any { term -> exercise.name.lowercase().contains(term) || exercise.bodyPart.lowercase().contains(term) }
        }
    }

    private suspend fun recentVolumeByMuscleGroup(catalog: List<Exercise>): Map<String, Int> {
        val sessions = ExerciseSessionRepository(database).getAllSessions().first()
        val cutoff = System.currentTimeMillis() - 28L * 24 * 60 * 60 * 1000
        val exerciseByName = catalog.associateBy { it.name }
        val counts = mutableMapOf<String, Int>()
        sessions.filter { it.performedAt >= cutoff }.forEach { session ->
            exerciseByName[session.exerciseId]?.muscleGroups?.forEach { group ->
                counts[group] = (counts[group] ?: 0) + 1
            }
        }
        return counts
    }

    private fun buildGenerationPrompt(profile: UserProfile?, catalog: List<Exercise>): String {
        val catalogLines = catalog.joinToString("\n") { "- ${it.name} (${it.bodyPart}, ${it.exerciseType}, ${it.category})" }
        return """
            Profile:
            - Experience: ${profile?.trainingExperience ?: "unknown"}
            - Preferred split: ${profile?.trainingSplit ?: "no preference"}
            - Session length: ${profile?.sessionLengthPreference ?: "unknown"}
            - Priority areas: ${profile?.focusAreas?.joinToString(", ").orEmpty()}

            Available exercises (you may ONLY use names from this exact list - anything else will be discarded):
            $catalogLines
        """.trimIndent()
    }

    private suspend fun buildRevisionPrompt(catalog: List<Exercise>): String? {
        val sessions = ExerciseSessionRepository(database).getAllSessions().first()
        if (sessions.size < 4) return null // not enough signal for a meaningful revision

        val volumeByGroup = recentVolumeByMuscleGroup(catalog)
        val bodyWeightEntries = BodyWeightRepository(database).getFrom(LocalDate.now().minusMonths(1)).first()
        val weightTrend = if (bodyWeightEntries.size >= 2) {
            "%.1f".format(bodyWeightEntries.last().weightKg - bodyWeightEntries.first().weightKg) + "kg over the last month"
        } else "insufficient data"

        val trainedAt = mutableMapOf<String, MutableList<Long>>()
        val exerciseByName = catalog.associateBy { it.name }
        sessions.forEach { session ->
            exerciseByName[session.exerciseId]?.muscleGroups?.forEach { group ->
                trainedAt.getOrPut(group) { mutableListOf() }.add(session.performedAt)
            }
        }
        val untrainedGroups = MuscleFatigue.calculate(trainedAt)
            .filter { it.level == MuscleFatigue.Level.UNTRAINED || (it.daysSinceTrained ?: 0) > 14 }
            .map { it.muscleGroup }

        return """
            Recent training summary (last 28 days):
            - Sets per muscle group: ${volumeByGroup.entries.joinToString(", ") { "${it.key}=${it.value}" }}
            - Muscle groups not trained recently: ${untrainedGroups.joinToString(", ").ifBlank { "none" }}
            - Body-weight trend: $weightTrend
            - Total sessions logged: ${sessions.size}

            Available exercises: ${catalog.joinToString(", ") { it.name }}
        """.trimIndent()
    }

    private val generationSystemPrompt = """
        You are a fitness programming assistant. Propose a structured weekly training plan.
        HARD RULE: every exerciseId you return MUST be copied exactly from the supplied list. Never invent an exercise name.
        Never give medical, injury-rehabilitation, or diagnostic advice.
        Where your rationale would be speculative, omit it rather than inventing a confident-sounding reason.
        progressionRule must be exactly one of: NONE, LINEAR, GREYSKULL_LP, DOUBLE_PROGRESSION, TIME_BASED.
        dayOfWeek is 1=Monday..7=Sunday.
        Respond with ONLY this JSON shape, no markdown fences, no commentary:
        {"planName":"string","rationale":"one short paragraph","weeklyPlan":[{"dayOfWeek":1,"routineName":"string"}],"routines":[{"name":"string","progressionRule":"NONE","exercises":[{"exerciseId":"string","sets":3,"repRangeMin":8,"repRangeMax":12,"supersetGroup":null,"why":"one line"}]}]}
    """.trimIndent()

    private val revisionSystemPrompt = """
        You are a fitness programming assistant reviewing a trainee's recent history.
        Propose a small number of specific changes as a diff, not a replacement plan.
        Never give medical, injury-rehabilitation, or diagnostic advice.
        Only reference exercises from the supplied list.
        Respond with ONLY this JSON shape, no markdown fences, no commentary:
        {"summary":"one short paragraph","items":[{"kind":"SWAP","routineName":"string","oldExerciseId":"string","newExerciseId":"string","why":"one line"},{"kind":"ADJUST","routineName":"string","exerciseId":"string","newSets":3,"why":"one line"},{"kind":"ADD","routineName":"string","exerciseId":"string","sets":3,"repRangeMin":8,"repRangeMax":12,"why":"one line"}]}
    """.trimIndent()

    private suspend fun requestJson(userContent: String): String? {
        val apiUrl = preferenceManager.aiCoachApiUrl
        if (apiUrl.isBlank()) return null
        val result = AiCoachApiClient.requestSetAnalysis(
            apiUrl = apiUrl,
            apiKey = preferenceManager.aiCoachApiKey,
            model = preferenceManager.aiCoachModel,
            systemPrompt = if (userContent.contains("Recent training summary")) revisionSystemPrompt else generationSystemPrompt,
            userContent = userContent
        )
        return result.getOrNull()?.let(::extractJsonObject)
    }

    /** Strips markdown fences a model may add despite instructions not to. */
    private fun extractJsonObject(raw: String): String {
        val trimmed = raw.trim().removePrefix("```json").removePrefix("```").removeSuffix("```").trim()
        val start = trimmed.indexOf('{')
        val end = trimmed.lastIndexOf('}')
        return if (start >= 0 && end > start) trimmed.substring(start, end + 1) else trimmed
    }

    private fun parseRevision(raw: String): PlanRevision {
        val obj = org.json.JSONObject(raw)
        val summary = obj.optString("summary", "")
        val items = mutableListOf<PlanDiffItem>()
        val array = obj.optJSONArray("items") ?: org.json.JSONArray()
        for (i in 0 until array.length()) {
            val item = array.getJSONObject(i)
            when (item.optString("kind")) {
                "SWAP" -> items += PlanDiffItem.SwapExercise(
                    item.getString("routineName"), item.getString("oldExerciseId"),
                    item.getString("newExerciseId"), item.optString("why")
                )
                "ADJUST" -> items += PlanDiffItem.AdjustVolume(
                    item.getString("routineName"), item.getString("exerciseId"),
                    item.getInt("newSets"), item.optString("why")
                )
                "ADD" -> items += PlanDiffItem.AddExercise(
                    item.getString("routineName"), item.getString("exerciseId"), item.getInt("sets"),
                    item.getInt("repRangeMin"), item.getInt("repRangeMax"), item.optString("why")
                )
            }
        }
        return PlanRevision(summary, items)
    }
}
